# Generated by Django 5.1.5 on 2025-02-05 11:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelApp', '0002_remove_customer_check_in_remove_customer_check_out_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='Room',
            field=models.ForeignKey(limit_choices_to={'Room_status': 'Available'}, on_delete=django.db.models.deletion.CASCADE, to='HotelApp.room'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='room',
            field=models.ForeignKey(limit_choices_to={'Room_status': 'Available'}, on_delete=django.db.models.deletion.CASCADE, to='HotelApp.room'),
        ),
        migrations.AlterField(
            model_name='room',
            name='Price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='room',
            name='Room_num',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='Room_type',
            field=models.CharField(choices=[('Single', 'Single'), ('Double', 'Double'), ('Suite', 'Suite')], default='please selete typr room', max_length=100),
        ),
    ]
